---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: grifon4ik/pacman:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/pacman
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
